#!/bin/bash

set -o errexit
set -o nounset

# wait for migrations applied
sleep 5
set_database_url() {
  postgres_password=$(grep 'postgres_password' /passwords/password.txt | cut -d '=' -f 2)

  # Set DATABASE_URL environment variable
  database_url="postgres://dbtuser:$postgres_password@postgres:5432/analytics"
  export DATABASE_URL="$database_url"

}
set_database_url
celery -A config.celery_app worker -l INFO
